Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -1,4 +1,4 @@
-name: iOS starter workflow
+name: iOS Build and Test Workflow
 
 on:
   push:
@@ -8,35 +8,43 @@ on:
 
 jobs:
   build-and-test:
-    name: Build and Test default scheme using any available iPhone simulator
+    name: Build and Test
     runs-on: macos-latest
 
     steps:
-      - name: Checkout
+      - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Set Default Scheme
-        id: set_scheme
-        run: |
-          scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo "Using default scheme: $scheme"
-          echo $scheme >default
-          echo "scheme=$scheme" >> $GITHUB_ENV
-
-      - name: Cache Swift Package Manager packages
+      - name: Cache Dependencies
         uses: actions/cache@v2
         with:
           path: |
+            ~/Library/Caches/SwiftPM
+            ~/Library/Caches/CocoaPods
             ~/Library/Caches/org.swift.swiftpm
             ~/.swiftpm
           key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
           restore-keys: |
             ${{ runner.os }}-swift-
 
-      - name: Build
+      - name: Install Xcode Dependencies
+        run: xcode-select -s /Applications/Xcode_15.4.app
+
+      - name: Set Default Scheme
+        id: set_scheme
         run: |
-          echo "Using scheme: ${{ env.scheme }}"
+          scheme_list=$(xcodebuild -list -json | tr -d "\n")
+          if [[ -z "$scheme_list" || "$scheme_list" == "null" ]]; then
+            echo "Failed to list schemes, exiting..."
+            exit 1
+          fi
+          scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
+          echo "Using default scheme: $scheme"
+          echo "scheme=$scheme" >> $GITHUB_ENV
+
+      - name: Build Project
+        run: |
+          echo "Building scheme: ${{ env.scheme }}"
           max_retries=3
           count=0
           until xcodebuild build-for-testing -scheme "${{ env.scheme }}" -destination "platform=iOS Simulator,name=Any available iPhone simulator"; do
@@ -49,9 +57,9 @@ jobs:
             sleep 15
           done
 
-      - name: Test
+      - name: Run Tests
         run: |
-          echo "Using scheme: ${{ env.scheme }}"
+          echo "Testing scheme: ${{ env.scheme }}"
           max_retries=3
           count=0
           until xcodebuild test-without-building -scheme "${{ env.scheme }}" -destination "platform=iOS Simulator,name=Any available iPhone simulator"; do
